### ISSUE TITLE
input_label not found

### ISSUE THREAD

**Issue by muster021** [skalavala/smarthome#42]
Hi!

Just upgraded to 0.84.0 and my previously working birthday package is broken!

018-12-12 19:21:34 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.input_label. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 92, in get_component
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/input_label.py", line 41, in <module>
    from homeassistant.helpers.restore_state import async_get_last_state
ImportError: cannot import name 'async_get_last_state'
2018-12-12 19:21:34 ERROR (MainThread) [homeassistant.loader] Unable to find component input_label
2018-12-12 19:21:34 ERROR (MainThread) [homeassistant.config] Package birthday setup failed. Component input_label does not exist (See /config/packages/birthday.yaml:9). 

I have the component in custom_components, and as I said, it has been working for months. Is it a dependency issue?

**Comment by typhoonss92** [comment]
First I would like to say thanks for making the birthday card it is awesome for the kids. But I too have the same issue after the upgrade, I just put in a github request in home-assistant for it. Just letting you know. Thanks

**Comment by skalavala** [comment]
Custom component updated and tested. Closing the issue!
